### PR TITLE
Add upload to blob storage and hooked up mediatr. Fixes #8

### LINKED ISSUE #8: Move uploaded files into blob storage

### PR DESCRIPTION
**Pull request by stimms**

### CODE REVIEW

**Comment by MisterJames** [comment]
Hrm...I'm seeing a wall of red on all touched files. Maybe we should sync up our VS/Git settings?

**Comment by stimms** [comment]
A wall of red? Just line endings?

**Comment by MisterJames** [comment]
Yeah, looks like I'm using CRLF I guess, and you've got LF?

On Sat, Oct 24, 2015 at 3:47 PM, Simon Timms notifications@github.com
wrote:

> A wall of red? Just line endings?
> On Oct 24, 2015 2:18 PM, "James Chambers" notifications@github.com
> wrote:
> 
> > Merged #15 <https://github.com/MisterJames/AzureImageProcessing/pull/15
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/MisterJames/AzureImageProcessing/pull/15#event-444643923
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MisterJames/AzureImageProcessing/pull/15#issuecomment-150849617
> .

## 

_James Chambers_
_Microsoft MVP Asp.Net/IIS_
Blog: http://jameschambers.com
Twitter: @CanadianJames

**Comment by stimms** [comment]
Oh okay I'll put in a configuration file later today.
On Oct 24, 2015 2:51 PM, "James Chambers" notifications@github.com wrote:

Yeah, looks like I'm using CRLF I guess, and you've got LF?

On Sat, Oct 24, 2015 at 3:47 PM, Simon Timms notifications@github.com
wrote:

> A wall of red? Just line endings?
> On Oct 24, 2015 2:18 PM, "James Chambers" notifications@github.com
> wrote:
> 
> > Merged #15 <https://github.com/MisterJames/AzureImageProcessing/pull/15
> > 
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> 
> https://github.com/MisterJames/AzureImageProcessing/pull/15#event-444643923
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/MisterJames/AzureImageProcessing/pull/15#issuecomment-150849617
> 
> .

## 

_James Chambers_
_Microsoft MVP Asp.Net/IIS_
Blog: http://jameschambers.com
Twitter: @CanadianJames

**Pull request merged**
